-- =====================================================================
-- KYC seed data: India's medals at Aichi-Nagoya 2026 (as of 2 October).
-- Source: Business Standard's medal list. PLEASE check every name before launch.
-- Run AFTER schema.sql. Squads like hockey and cricket have no players yet:
-- add them from the writer panel.
-- =====================================================================

insert into public.champions (slug, name, sport, state, hometown) values
  ('kamaljeet', 'Kamaljeet', 'Shooting', null, null),
  ('suruchi-singh', 'Suruchi Singh', 'Shooting', null, null),
  ('neeru-dhanda', 'Neeru Dhanda', 'Shooting', null, null),
  ('kiran-pahal', 'Kiran Pahal', 'Athletics', null, null),
  ('poovamma-mr', 'Poovamma MR', 'Athletics', null, null),
  ('prachi-choudhary', 'Prachi Choudhary', 'Athletics', null, null),
  ('vithya-ramraj', 'Vithya Ramraj', 'Athletics', null, null),
  ('jyothi-surekha-vennam', 'Jyothi Surekha Vennam', 'Archery', null, null),
  ('prithika-pradeep', 'Prithika Pradeep', 'Archery', null, null),
  ('chikitha-taniparthi', 'Chikitha Taniparthi', 'Archery', null, null),
  ('sahil-jadhav', 'Sahil Jadhav', 'Archery', null, null),
  ('ganesh-mani-ratnam-thirumuru', 'Ganesh Mani Ratnam Thirumuru', 'Archery', null, null),
  ('kushal-dalal', 'Kushal Dalal', 'Archery', null, null),
  ('kynan-chenai', 'Kynan Chenai', 'Shooting', null, null),
  ('ankita-bhakat', 'Ankita Bhakat', 'Archery', null, null),
  ('kumkum-mohod', 'Kumkum Mohod', 'Archery', null, null),
  ('kirti-sharma', 'Kirti Sharma', 'Archery', null, null),
  ('lovlina-borgohain', 'Lovlina Borgohain', 'Boxing', 'Assam', 'Golaghat'),
  ('parveen-hooda', 'Parveen Hooda', 'Boxing', null, null),
  ('ankush-panghal', 'Ankush Panghal', 'Boxing', null, null),
  ('sujeet-kalkal', 'Sujeet Kalkal', 'Wrestling', null, null),
  ('elavenil-valarivan', 'Elavenil Valarivan', 'Shooting', null, null),
  ('sonam-maskar', 'Sonam Maskar', 'Shooting', null, null),
  ('vidarsa-vinod', 'Vidarsa Vinod', 'Shooting', null, null),
  ('rudrankksh-patil', 'Rudrankksh Patil', 'Shooting', null, null),
  ('parth-mane', 'Parth Mane', 'Shooting', null, null),
  ('himanshu-dhillon', 'Himanshu Dhillon', 'Shooting', null, null),
  ('mirabai-chanu', 'Mirabai Chanu', 'Weightlifting', null, null),
  ('naorem-roshibina-devi', 'Naorem Roshibina Devi', 'Wushu', null, null),
  ('vishal-tk', 'Vishal TK', 'Athletics', null, null),
  ('manu-ts', 'Manu TS', 'Athletics', null, null),
  ('aishwary-pratap-singh-tomar', 'Aishwary Pratap Singh Tomar', 'Shooting', null, null),
  ('niraj-kumar', 'Niraj Kumar', 'Shooting', null, null),
  ('gulveer-singh', 'Gulveer Singh', 'Athletics', null, null),
  ('sawan-berwal', 'Sawan Berwal', 'Athletics', null, null),
  ('ashi-chouksey', 'Ashi Chouksey', 'Shooting', null, null),
  ('tilottama-sen', 'Tilottama Sen', 'Shooting', null, null),
  ('tajinderpal-singh-toor', 'Tajinderpal Singh Toor', 'Athletics', null, null),
  ('abhay-singh', 'Abhay Singh', 'Squash', null, null),
  ('anahat-singh', 'Anahat Singh', 'Squash', null, null),
  ('ancy-sojan', 'Ancy Sojan', 'Athletics', null, null),
  ('sarvesh-kushare', 'Sarvesh Kushare', 'Athletics', null, null),
  ('esha-singh', 'Esha Singh', 'Shooting', null, null),
  ('murali-sreeshankar', 'Murali Sreeshankar', 'Athletics', null, null),
  ('yash-vir-singh', 'Yash Vir Singh', 'Athletics', null, null),
  ('manisha-keer', 'Manisha Keer', 'Shooting', null, null),
  ('aashima-ahlawat', 'Aashima Ahlawat', 'Shooting', null, null),
  ('prince-kurisinkal-noble', 'Prince Kurisinkal Noble', 'Sailing', null, null),
  ('manu-francis', 'Manu Francis', 'Sailing', null, null),
  ('nitesh-kumar', 'Nitesh Kumar', 'Wrestling', null, null),
  ('dhiraj-bommadevara', 'Dhiraj Bommadevara', 'Archery', null, null),
  ('yashdeep-bhoge', 'Yashdeep Bhoge', 'Archery', null, null),
  ('neeraj-chauhan', 'Neeraj Chauhan', 'Archery', null, null),
  ('suchika-tariyal', 'Suchika Tariyal', 'Mixed martial arts', null, null),
  ('parinaaz-dhaliwal', 'Parinaaz Dhaliwal', 'Shooting', null, null),
  ('raiza-dhillon', 'Raiza Dhillon', 'Shooting', null, null),
  ('maheshwari-chauhan', 'Maheshwari Chauhan', 'Shooting', null, null),
  ('anantjeet-singh-naruka', 'Anantjeet Singh Naruka', 'Shooting', null, null),
  ('bhavtegh-singh-gill', 'Bhavtegh Singh Gill', 'Shooting', null, null),
  ('mairaj-ahmad-khan', 'Mairaj Ahmad Khan', 'Shooting', null, null),
  ('jay-meena', 'Jay Meena', 'Soft tennis', null, null),
  ('satnam-singh', 'Satnam Singh', 'Rowing', null, null),
  ('salman-khan', 'Salman Khan', 'Rowing', null, null),
  ('seema-kumari', 'Seema Kumari', 'Athletics', null, null),
  ('diya-chitale', 'Diya Chitale', 'Table tennis', null, null),
  ('manush-shah', 'Manush Shah', 'Table tennis', null, null),
  ('manpreet-kaur', 'Manpreet Kaur', 'Athletics', null, null),
  ('baranica-elangovan', 'Baranica Elangovan', 'Athletics', null, null),
  ('joshna-chinappa', 'Joshna Chinappa', 'Squash', null, null),
  ('velavan-senthilkumar', 'Velavan Senthilkumar', 'Squash', null, null),
  ('haritha-bhadra', 'Haritha Bhadra', 'Athletics', null, null),
  ('tejaswin-shankar', 'Tejaswin Shankar', 'Athletics', null, null),
  ('parul-chaudhary', 'Parul Chaudhary', 'Athletics', null, null),
  ('pincky-balhara', 'Pincky Balhara', 'Kurash', null, null),
  ('rohit-yadav', 'Rohit Yadav', 'Athletics', null, null),
  ('narender-berwal', 'Narender Berwal', 'Boxing', null, null),
  ('gurindervir-singh', 'Gurindervir Singh', 'Athletics', null, null),
  ('sneha-ss', 'Sneha SS', 'Athletics', null, null),
  ('animesh-kujur', 'Animesh Kujur', 'Athletics', null, null),
  ('pooja-singh', 'Pooja Singh', 'Athletics', null, null),
  ('dharmveer-choudhary', 'Dharmveer Choudhary', 'Athletics', null, null),
  ('jay-kumar', 'Jay Kumar', 'Athletics', null, null),
  ('priya-ghanghas', 'Priya Ghanghas', 'Boxing', null, null),
  ('kapil-pokhariya', 'Kapil Pokhariya', 'Boxing', null, null),
  ('sunil-kumar', 'Sunil Kumar', 'Wrestling', null, null),
  ('tanvi-khanna', 'Tanvi Khanna', 'Squash', null, null),
  ('shameena-riaz', 'Shameena Riaz', 'Squash', null, null),
  ('veer-chotrani', 'Veer Chotrani', 'Squash', null, null),
  ('suraj-kumar-chand', 'Suraj Kumar Chand', 'Squash', null, null),
  ('harshita-tomar', 'Harshita Tomar', 'Sailing', null, null),
  ('shital-verma', 'Shital Verma', 'Sailing', null, null),
  ('nethra-kumanan', 'Nethra Kumanan', 'Sailing', null, null),
  ('malemnganba-singh-sorokhaibam', 'Malemnganba Singh Sorokhaibam', 'Sepaktakraw', null, null),
  ('ram-kumar-sharma', 'Ram Kumar Sharma', 'Sepaktakraw', null, null),
  ('bobby-kumar', 'Bobby Kumar', 'Sepaktakraw', null, null),
  ('akash-yumnam', 'Akash Yumnam', 'Sepaktakraw', null, null);

insert into public.teams (slug, name, sport) values
  ('india-womens-cricket-team', 'India women''s cricket team', 'Cricket'),
  ('mixed-10m-air-pistol-pair', 'Mixed 10m air pistol pair', 'Shooting'),
  ('india-womens-kabaddi-team', 'India women''s kabaddi team', 'Kabaddi'),
  ('india-mens-kabaddi-team', 'India men''s kabaddi team', 'Kabaddi'),
  ('womens-4x400m-relay-team', 'Women''s 4x400m relay team', 'Athletics'),
  ('womens-compound-archery-team', 'Women''s compound archery team', 'Archery'),
  ('mixed-compound-archery-pair', 'Mixed compound archery pair', 'Archery'),
  ('mens-compound-archery-team', 'Men''s compound archery team', 'Archery'),
  ('mixed-trap-pair', 'Mixed trap pair', 'Shooting'),
  ('womens-recurve-archery-team', 'Women''s recurve archery team', 'Archery'),
  ('india-womens-hockey-team', 'India women''s hockey team', 'Hockey'),
  ('womens-10m-air-rifle-team', 'Women''s 10m air rifle team', 'Shooting'),
  ('mens-10m-air-rifle-team', 'Men''s 10m air rifle team', 'Shooting'),
  ('mixed-4x400m-relay-team', 'Mixed 4x400m relay team', 'Athletics'),
  ('mens-50m-rifle-3-positions-team', 'Men''s 50m rifle 3 positions team', 'Shooting'),
  ('womens-50m-rifle-3-positions-team', 'Women''s 50m rifle 3 positions team', 'Shooting'),
  ('womens-trap-team', 'Women''s trap team', 'Shooting'),
  ('mens-skiff-crew', 'Men''s skiff crew', 'Sailing'),
  ('mixed-recurve-archery-pair', 'Mixed recurve archery pair', 'Archery'),
  ('mens-recurve-archery-team', 'Men''s recurve archery team', 'Archery'),
  ('womens-skeet-team', 'Women''s skeet team', 'Shooting'),
  ('mens-skeet-team', 'Men''s skeet team', 'Shooting'),
  ('india-mens-badminton-team', 'India men''s badminton team', 'Badminton'),
  ('mens-double-sculls-crew', 'Men''s double sculls crew', 'Rowing'),
  ('mixed-skeet-pair', 'Mixed skeet pair', 'Shooting'),
  ('table-tennis-mixed-doubles-pair', 'Table tennis mixed doubles pair', 'Table tennis'),
  ('squash-mixed-doubles-pair', 'Squash mixed doubles pair', 'Squash'),
  ('mixed-4x100m-relay-team', 'Mixed 4x100m relay team', 'Athletics'),
  ('mens-4x400m-relay-team', 'Men''s 4x400m relay team', 'Athletics'),
  ('womens-squash-team', 'Women''s squash team', 'Squash'),
  ('mens-squash-team', 'Men''s squash team', 'Squash'),
  ('womens-skiff-crew', 'Women''s skiff crew', 'Sailing'),
  ('mens-sepaktakraw-quadrant-team', 'Men''s sepaktakraw quadrant team', 'Sepaktakraw');

insert into public.team_members (team_id, champion_id, position)
select t.id, c.id, v.pos from (values
  ('mixed-10m-air-pistol-pair', 'kamaljeet', 0),
  ('mixed-10m-air-pistol-pair', 'suruchi-singh', 1),
  ('womens-4x400m-relay-team', 'kiran-pahal', 0),
  ('womens-4x400m-relay-team', 'poovamma-mr', 1),
  ('womens-4x400m-relay-team', 'prachi-choudhary', 2),
  ('womens-4x400m-relay-team', 'vithya-ramraj', 3),
  ('womens-compound-archery-team', 'jyothi-surekha-vennam', 0),
  ('womens-compound-archery-team', 'prithika-pradeep', 1),
  ('womens-compound-archery-team', 'chikitha-taniparthi', 2),
  ('mixed-compound-archery-pair', 'chikitha-taniparthi', 0),
  ('mixed-compound-archery-pair', 'sahil-jadhav', 1),
  ('mens-compound-archery-team', 'sahil-jadhav', 0),
  ('mens-compound-archery-team', 'ganesh-mani-ratnam-thirumuru', 1),
  ('mens-compound-archery-team', 'kushal-dalal', 2),
  ('mixed-trap-pair', 'kynan-chenai', 0),
  ('mixed-trap-pair', 'neeru-dhanda', 1),
  ('womens-recurve-archery-team', 'ankita-bhakat', 0),
  ('womens-recurve-archery-team', 'kumkum-mohod', 1),
  ('womens-recurve-archery-team', 'kirti-sharma', 2),
  ('womens-10m-air-rifle-team', 'elavenil-valarivan', 0),
  ('womens-10m-air-rifle-team', 'sonam-maskar', 1),
  ('womens-10m-air-rifle-team', 'vidarsa-vinod', 2),
  ('mens-10m-air-rifle-team', 'rudrankksh-patil', 0),
  ('mens-10m-air-rifle-team', 'parth-mane', 1),
  ('mens-10m-air-rifle-team', 'himanshu-dhillon', 2),
  ('mixed-4x400m-relay-team', 'vishal-tk', 0),
  ('mixed-4x400m-relay-team', 'poovamma-mr', 1),
  ('mixed-4x400m-relay-team', 'manu-ts', 2),
  ('mixed-4x400m-relay-team', 'vithya-ramraj', 3),
  ('mens-50m-rifle-3-positions-team', 'aishwary-pratap-singh-tomar', 0),
  ('mens-50m-rifle-3-positions-team', 'rudrankksh-patil', 1),
  ('mens-50m-rifle-3-positions-team', 'niraj-kumar', 2),
  ('womens-50m-rifle-3-positions-team', 'vidarsa-vinod', 0),
  ('womens-50m-rifle-3-positions-team', 'ashi-chouksey', 1),
  ('womens-50m-rifle-3-positions-team', 'tilottama-sen', 2),
  ('womens-trap-team', 'neeru-dhanda', 0),
  ('womens-trap-team', 'manisha-keer', 1),
  ('womens-trap-team', 'aashima-ahlawat', 2),
  ('mens-skiff-crew', 'prince-kurisinkal-noble', 0),
  ('mens-skiff-crew', 'manu-francis', 1),
  ('mixed-recurve-archery-pair', 'kumkum-mohod', 0),
  ('mixed-recurve-archery-pair', 'dhiraj-bommadevara', 1),
  ('mens-recurve-archery-team', 'dhiraj-bommadevara', 0),
  ('mens-recurve-archery-team', 'yashdeep-bhoge', 1),
  ('mens-recurve-archery-team', 'neeraj-chauhan', 2),
  ('womens-skeet-team', 'parinaaz-dhaliwal', 0),
  ('womens-skeet-team', 'raiza-dhillon', 1),
  ('womens-skeet-team', 'maheshwari-chauhan', 2),
  ('mens-skeet-team', 'anantjeet-singh-naruka', 0),
  ('mens-skeet-team', 'bhavtegh-singh-gill', 1),
  ('mens-skeet-team', 'mairaj-ahmad-khan', 2),
  ('mens-double-sculls-crew', 'satnam-singh', 0),
  ('mens-double-sculls-crew', 'salman-khan', 1),
  ('mixed-skeet-pair', 'anantjeet-singh-naruka', 0),
  ('mixed-skeet-pair', 'parinaaz-dhaliwal', 1),
  ('table-tennis-mixed-doubles-pair', 'diya-chitale', 0),
  ('table-tennis-mixed-doubles-pair', 'manush-shah', 1),
  ('squash-mixed-doubles-pair', 'joshna-chinappa', 0),
  ('squash-mixed-doubles-pair', 'velavan-senthilkumar', 1),
  ('mixed-4x100m-relay-team', 'gurindervir-singh', 0),
  ('mixed-4x100m-relay-team', 'sneha-ss', 1),
  ('mixed-4x100m-relay-team', 'animesh-kujur', 2),
  ('mixed-4x100m-relay-team', 'haritha-bhadra', 3),
  ('mens-4x400m-relay-team', 'dharmveer-choudhary', 0),
  ('mens-4x400m-relay-team', 'manu-ts', 1),
  ('mens-4x400m-relay-team', 'jay-kumar', 2),
  ('mens-4x400m-relay-team', 'vishal-tk', 3),
  ('womens-squash-team', 'anahat-singh', 0),
  ('womens-squash-team', 'joshna-chinappa', 1),
  ('womens-squash-team', 'tanvi-khanna', 2),
  ('womens-squash-team', 'shameena-riaz', 3),
  ('mens-squash-team', 'abhay-singh', 0),
  ('mens-squash-team', 'veer-chotrani', 1),
  ('mens-squash-team', 'velavan-senthilkumar', 2),
  ('mens-squash-team', 'suraj-kumar-chand', 3),
  ('womens-skiff-crew', 'harshita-tomar', 0),
  ('womens-skiff-crew', 'shital-verma', 1),
  ('mens-sepaktakraw-quadrant-team', 'malemnganba-singh-sorokhaibam', 0),
  ('mens-sepaktakraw-quadrant-team', 'ram-kumar-sharma', 1),
  ('mens-sepaktakraw-quadrant-team', 'bobby-kumar', 2),
  ('mens-sepaktakraw-quadrant-team', 'akash-yumnam', 3)
) as v(team_slug, champ_slug, pos)
join public.teams t on t.slug = v.team_slug
join public.champions c on c.slug = v.champ_slug;

insert into public.medals (medal, sport, event, won_on, champion_id)
select v.medal::public.medal_kind, v.sport, v.event, v.won_on, c.id from (values
  ('gold', 'Shooting', 'Women''s trap', null, 'neeru-dhanda'),
  ('gold', 'Boxing', 'Women''s 75 kg', date '2026-10-02', 'lovlina-borgohain'),
  ('gold', 'Boxing', 'Women''s 65 kg', date '2026-10-02', 'parveen-hooda'),
  ('gold', 'Boxing', 'Men''s 80 kg', date '2026-10-02', 'ankush-panghal'),
  ('gold', 'Wrestling', 'Men''s freestyle 65 kg', date '2026-10-02', 'sujeet-kalkal'),
  ('silver', 'Shooting', 'Women''s 10m air rifle', date '2026-09-20', 'elavenil-valarivan'),
  ('silver', 'Shooting', 'Men''s 10m air rifle', date '2026-09-21', 'himanshu-dhillon'),
  ('silver', 'Weightlifting', 'Women''s 49 kg', date '2026-09-23', 'mirabai-chanu'),
  ('silver', 'Wushu', 'Women''s sanda 60 kg', date '2026-09-24', 'naorem-roshibina-devi'),
  ('silver', 'Athletics', 'Men''s 10,000m', date '2026-09-25', 'gulveer-singh'),
  ('silver', 'Athletics', 'Men''s marathon', date '2026-09-26', 'sawan-berwal'),
  ('silver', 'Athletics', 'Men''s shot put', date '2026-09-26', 'tajinderpal-singh-toor'),
  ('silver', 'Squash', 'Men''s singles', date '2026-09-27', 'abhay-singh'),
  ('silver', 'Squash', 'Women''s singles', date '2026-09-27', 'anahat-singh'),
  ('silver', 'Athletics', 'Women''s long jump', date '2026-09-27', 'ancy-sojan'),
  ('silver', 'Athletics', 'Men''s high jump', date '2026-09-27', 'sarvesh-kushare'),
  ('silver', 'Shooting', 'Women''s 25m pistol', date '2026-09-28', 'esha-singh'),
  ('silver', 'Athletics', 'Men''s 1500m', date '2026-09-27', 'gulveer-singh'),
  ('silver', 'Athletics', 'Men''s long jump', date '2026-09-28', 'murali-sreeshankar'),
  ('silver', 'Athletics', 'Men''s javelin throw', date '2026-09-28', 'yash-vir-singh'),
  ('silver', 'Wrestling', 'Men''s Greco-Roman 97 kg', date '2026-10-01', 'nitesh-kumar'),
  ('bronze', 'Shooting', 'Men''s 10m air rifle', date '2026-09-21', 'rudrankksh-patil'),
  ('bronze', 'Mixed martial arts', 'Women''s traditional 60 kg', date '2026-09-21', 'suchika-tariyal'),
  ('bronze', 'Soft tennis', 'Men''s singles', date '2026-09-23', 'jay-meena'),
  ('bronze', 'Athletics', 'Women''s 10,000m', date '2026-09-24', 'seema-kumari'),
  ('bronze', 'Athletics', 'Women''s shot put', date '2026-09-25', 'manpreet-kaur'),
  ('bronze', 'Athletics', 'Women''s pole vault', date '2026-09-25', 'baranica-elangovan'),
  ('bronze', 'Athletics', 'Women''s 400m', date '2026-09-26', 'prachi-choudhary'),
  ('bronze', 'Athletics', 'Women''s 200m', date '2026-09-27', 'haritha-bhadra'),
  ('bronze', 'Athletics', 'Men''s decathlon', date '2026-09-27', 'tejaswin-shankar'),
  ('bronze', 'Athletics', 'Women''s 3000m steeplechase', date '2026-09-27', 'parul-chaudhary'),
  ('bronze', 'Kurash', 'Women''s 78 kg', date '2026-09-28', 'pincky-balhara'),
  ('bronze', 'Athletics', 'Women''s 400m hurdles', date '2026-09-28', 'vithya-ramraj'),
  ('bronze', 'Athletics', 'Women''s 5000m', date '2026-09-28', 'parul-chaudhary'),
  ('bronze', 'Athletics', 'Men''s javelin throw', date '2026-09-28', 'rohit-yadav'),
  ('bronze', 'Boxing', 'Men''s +90 kg', null, 'narender-berwal'),
  ('bronze', 'Athletics', 'Men''s 5000m', null, 'gulveer-singh'),
  ('bronze', 'Athletics', 'Women''s high jump', null, 'pooja-singh'),
  ('bronze', 'Boxing', 'Women''s 60 kg', date '2026-09-30', 'priya-ghanghas'),
  ('bronze', 'Boxing', 'Men''s 90 kg', date '2026-09-30', 'kapil-pokhariya'),
  ('bronze', 'Wrestling', 'Men''s Greco-Roman 87 kg', date '2026-09-30', 'sunil-kumar'),
  ('bronze', 'Archery', 'Men''s compound individual', date '2026-10-01', 'ganesh-mani-ratnam-thirumuru'),
  ('bronze', 'Sailing', 'Women''s dinghy', date '2026-10-02', 'nethra-kumanan')
) as v(medal, sport, event, won_on, champ_slug)
join public.champions c on c.slug = v.champ_slug;

insert into public.medals (medal, sport, event, won_on, team_id)
select v.medal::public.medal_kind, v.sport, v.event, v.won_on, t.id from (values
  ('gold', 'Cricket', 'Women''s T20', date '2026-09-22', 'india-womens-cricket-team'),
  ('gold', 'Shooting', 'Mixed team 10m air pistol', date '2026-09-25', 'mixed-10m-air-pistol-pair'),
  ('gold', 'Kabaddi', 'Women''s kabaddi', date '2026-09-26', 'india-womens-kabaddi-team'),
  ('gold', 'Kabaddi', 'Men''s kabaddi', date '2026-09-26', 'india-mens-kabaddi-team'),
  ('gold', 'Athletics', 'Women''s 4x400m relay', null, 'womens-4x400m-relay-team'),
  ('gold', 'Archery', 'Women''s compound team', date '2026-09-30', 'womens-compound-archery-team'),
  ('gold', 'Archery', 'Mixed compound team', date '2026-09-30', 'mixed-compound-archery-pair'),
  ('gold', 'Archery', 'Men''s compound team', date '2026-09-30', 'mens-compound-archery-team'),
  ('gold', 'Shooting', 'Mixed trap team', date '2026-09-30', 'mixed-trap-pair'),
  ('gold', 'Archery', 'Women''s recurve team', date '2026-10-02', 'womens-recurve-archery-team'),
  ('gold', 'Hockey', 'Women''s hockey', date '2026-10-02', 'india-womens-hockey-team'),
  ('silver', 'Shooting', 'Women''s 10m air rifle team', date '2026-09-20', 'womens-10m-air-rifle-team'),
  ('silver', 'Shooting', 'Men''s 10m air rifle team', date '2026-09-21', 'mens-10m-air-rifle-team'),
  ('silver', 'Athletics', 'Mixed 4x400m relay', date '2026-09-24', 'mixed-4x400m-relay-team'),
  ('silver', 'Shooting', 'Men''s 50m rifle 3 positions team', date '2026-09-25', 'mens-50m-rifle-3-positions-team'),
  ('silver', 'Shooting', 'Women''s 50m rifle 3 positions team', date '2026-09-26', 'womens-50m-rifle-3-positions-team'),
  ('silver', 'Shooting', 'Women''s trap team', null, 'womens-trap-team'),
  ('silver', 'Sailing', 'Men''s skiff', date '2026-10-01', 'mens-skiff-crew'),
  ('silver', 'Archery', 'Mixed recurve team', date '2026-10-02', 'mixed-recurve-archery-pair'),
  ('silver', 'Archery', 'Men''s recurve team', date '2026-10-02', 'mens-recurve-archery-team'),
  ('bronze', 'Shooting', 'Women''s skeet team', date '2026-09-23', 'womens-skeet-team'),
  ('bronze', 'Shooting', 'Men''s skeet team', date '2026-09-23', 'mens-skeet-team'),
  ('bronze', 'Badminton', 'Men''s team', date '2026-09-23', 'india-mens-badminton-team'),
  ('bronze', 'Rowing', 'Men''s double sculls', date '2026-09-24', 'mens-double-sculls-crew'),
  ('bronze', 'Shooting', 'Mixed skeet team', date '2026-09-24', 'mixed-skeet-pair'),
  ('bronze', 'Table tennis', 'Mixed doubles', date '2026-09-25', 'table-tennis-mixed-doubles-pair'),
  ('bronze', 'Squash', 'Mixed doubles', date '2026-09-26', 'squash-mixed-doubles-pair'),
  ('bronze', 'Athletics', 'Mixed 4x100m relay', null, 'mixed-4x100m-relay-team'),
  ('bronze', 'Athletics', 'Men''s 4x400m relay', null, 'mens-4x400m-relay-team'),
  ('bronze', 'Squash', 'Women''s team', date '2026-10-01', 'womens-squash-team'),
  ('bronze', 'Squash', 'Men''s team', date '2026-10-01', 'mens-squash-team'),
  ('bronze', 'Sailing', 'Women''s skiff', date '2026-10-01', 'womens-skiff-crew'),
  ('bronze', 'Sepaktakraw', 'Men''s quadrant', date '2026-10-02', 'mens-sepaktakraw-quadrant-team')
) as v(medal, sport, event, won_on, team_slug)
join public.teams t on t.slug = v.team_slug;

-- Check: should return gold 16, silver 25, bronze 35.
select medal, count(*) from public.medals group by medal order by medal;
